#!/usr/bin/env python3
"""Interview Prep Agent (roster B22) — role-specific prep from canonical context.

What this is
------------
A deterministic pack builder. It consumes

1. a canonical **JobBrief** produced by ``career-ops/job_intelligence.py``
   (verbatim posting lines with source lines, eligibility resolution, risks and
   cited company facts),
2. the canonical owner sources inside the existing Career Ops install
   (``cv.md``, ``config/profile.yml``, ``config/cv-facts.json``), and
3. optionally a cited research file through the briefing module's own provider
   interface (``job_intelligence.research_brief``),

and produces, for one role:

* technical preparation prompts derived from the posting's own requirement lines,
* behavioural preparation prompts tied to the posting's responsibility lines,
* a likely-question list,
* evidence-backed talking points that quote canonical CV lines verbatim,
* questions to ask the employer drawn from the brief's own unknowns,
* an explicit unknown / owner-input list.

Truth rules (enforced, not decorative)
-------------------------------------
* A question is a **preparation prompt generated by a deterministic template**.
  It is never presented as a question the employer supplied, and every question
  item carries that disclaimer plus the verbatim posting line it came from.
* A talking point **quotes a canonical CV line verbatim** and carries its
  ``cv.md`` source line. Nothing is paraphrased, summarised or extended.
* Where the posting asks for something the canonical sources do not evidence,
  the result is ``owner_input_required`` — never a claim about the candidate.
  ``candidate_claims`` is always empty and a first-person-claim scanner fails
  the pack if one ever appears in generated text.
* Company/role context comes only from the brief's cited facts. With no provider
  the pack records ``research_needed`` and adds no company fact.
* No employer, recruiter or candidate is contacted; nothing is posted, sent,
  scheduled or submitted; no browser, GUI or network call is made.

CLI
  python career-ops/interview_prep.py pack --brief BRIEF.json [--research-file F]
                                        [--out DIR] [--stamp S]
  python career-ops/interview_prep.py from-job --region uk --jd-file JD.txt
                                        [--id ID | --url URL | --row N
                                         | --pipeline-index N | --job-record REC.json]
                                        [--research-file F] [--out DIR] [--stamp S]
  python career-ops/interview_prep.py validate --pack PACK.json
  python career-ops/interview_prep.py schema
  python career-ops/interview_prep.py status

Input and output paths stay separate: ``--brief``/``--jd-file``/``--job-record``/
``--research-file`` are read-only and the command refuses to run if an output
path would overwrite one of its own inputs.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
from pathlib import Path

CAREER_OPS_DIR = Path(__file__).resolve().parent
CONTROL_PLANE = CAREER_OPS_DIR.parent
DEFAULT_CONFIG = CAREER_OPS_DIR / "interview_prep_config.json"

sys.path.insert(0, str(CAREER_OPS_DIR))

import cv_workflow as cvw  # noqa: E402
import job_intelligence as ji  # noqa: E402
import tracker_writer as tw  # noqa: E402

emit = cvw.emit
now_utc = cvw.now_utc
read_text = cvw.read_text
sha256_file = cvw.sha256_file
sha256_text = cvw.sha256_text

QUOTE_SOURCE = "cv.md"


# --------------------------------------------------------------------------- #
# configuration / plumbing
# --------------------------------------------------------------------------- #

def load_config(path: str | Path | None = None) -> dict:
    p = Path(path or DEFAULT_CONFIG)
    cfg = json.loads(read_text(p))
    cfg["_config_path"] = str(p)
    return cfg


def cv_config(cfg: dict) -> dict:
    return cvw.load_config(CONTROL_PLANE / cfg["cv_workflow_config"])


def ji_config(cfg: dict) -> dict:
    return ji.load_config(CONTROL_PLANE / cfg["job_intelligence_config"])


def profiles_path(cfg: dict) -> Path:
    return CONTROL_PLANE / cfg["regional_profiles"]


def runtime_dir(cfg: dict) -> Path:
    d = CONTROL_PLANE / cfg["runtime_dir"]
    d.mkdir(parents=True, exist_ok=True)
    return d


def pack_schema_path(cfg: dict) -> Path:
    return CONTROL_PLANE / cfg["pack_schema"]


def _limits(cfg: dict) -> dict:
    return cfg.get("limits", {})


# --------------------------------------------------------------------------- #
# the brief and the canonical owner sources
# --------------------------------------------------------------------------- #

class BriefError(ValueError):
    """The supplied document is not usable as a JobBrief."""


def load_brief(path: str | Path) -> dict:
    """Read a JobBrief and refuse anything that is not one.

    The prep pack's whole provenance chain depends on the brief being the
    extractive artifact ``job_intelligence.py`` produced, so a file that merely
    *looks* like JSON is rejected rather than guessed at.
    """
    p = Path(path)
    if not p.exists():
        raise BriefError(f"brief not found: {p}")
    doc = json.loads(read_text(p))
    if not isinstance(doc, dict):
        raise BriefError("brief must be a JSON object")
    missing = [k for k in ("brief_id", "job", "requirements", "eligibility",
                           "source_supported_facts") if k not in doc]
    if missing:
        raise BriefError(
            "not a JobBrief: missing " + ", ".join(missing)
            + " (produce one with career-ops/job_intelligence.py brief)")
    if doc.get("candidate_claims"):
        raise BriefError("brief carries candidate_claims, which must be empty")
    return doc


def canonical_evidence(cfg: dict) -> list[dict]:
    """Every non-empty canonical CV line, with its cv.md line number."""
    cv_path = cvw.source_paths(cv_config(cfg))["cv_md"]
    text = read_text(cv_path)
    out: list[dict] = []
    for section in cvw.parse_cv_markdown(text):
        for line in section["lines"]:
            if line["kind"] == "blank" or not line["text"].strip():
                continue
            out.append({
                "quote": line["text"],
                "source": QUOTE_SOURCE,
                "source_line": line["no"],
                "section": section["heading"],
                "kind": line["kind"],
            })
    return out


def canonical_line_index(cfg: dict) -> dict[int, str]:
    cv_path = cvw.source_paths(cv_config(cfg))["cv_md"]
    index = {}
    for no, raw in enumerate(read_text(cv_path).splitlines(), start=1):
        index[no] = raw.strip()
    return index


# --------------------------------------------------------------------------- #
# deterministic question generation
# --------------------------------------------------------------------------- #

def _category_for(text: str, cfg: dict) -> dict:
    folded = (text or "").casefold()
    for cat in cfg["question_bank"]["categories"]:
        if cat.get("match") and re.search(cat["match"], folded):
            return cat
    return {"id": "general_requirement", "match": None,
            "technical": cfg["question_bank"]["fallback_technical"]}


def technical_questions(brief: dict, cfg: dict) -> list[dict]:
    """One preparation prompt per essential requirement, plus one per responsibility."""
    out: list[dict] = []
    for req in brief.get("requirements", []):
        if req.get("kind") != "essential":
            continue
        category = _category_for(req.get("text"), cfg)
        out.append({
            "id": f"tech-req-{len(out) + 1}",
            "bucket": "technical",
            "category": category["id"],
            "prompt": category["technical"],
            "basis": {
                "kind": "posting_requirement",
                "text": req["text"],
                "source_line": req["source_line"],
                "source_section": req.get("source_section"),
                "requirement_kind": req.get("kind"),
            },
            "derivation": "deterministic template over the posting's own requirement line",
            "employer_supplied": False,
            "note": "This is a preparation prompt generated by this tool, NOT a question the "
                    "employer supplied.",
        })
    for resp in brief.get("responsibilities", []):
        category = _category_for(resp.get("text"), cfg)
        out.append({
            "id": f"tech-resp-{len(out) + 1}",
            "bucket": "technical",
            "category": category["id"],
            "prompt": category["technical"],
            "basis": {
                "kind": "posting_responsibility",
                "text": resp["text"],
                "source_line": resp["source_line"],
                "source_section": resp.get("source_section"),
            },
            "derivation": "deterministic template over the posting's own responsibility line",
            "employer_supplied": False,
            "note": "Preparation prompt generated by this tool, NOT an employer-supplied question.",
        })
    return out[: int(_limits(cfg).get("max_technical_questions", 18))]


def behavioural_questions(brief: dict, cfg: dict) -> list[dict]:
    """Behavioural prompts; each is tied to a posting responsibility when one matches."""
    responsibilities = brief.get("responsibilities", [])
    out: list[dict] = []
    for bank in cfg["question_bank"]["behavioural"]:
        linked = None
        pattern = bank.get("match")
        if pattern:
            for resp in responsibilities:
                if re.search(pattern, (resp.get("text") or "").casefold()):
                    linked = resp
                    break
        out.append({
            "id": f"behav-{bank['id']}",
            "bucket": "behavioural",
            "theme": bank["id"],
            "prompt": bank["question"],
            "basis": ({"kind": "posting_responsibility", "text": linked["text"],
                       "source_line": linked["source_line"],
                       "source_section": linked.get("source_section")} if linked else
                      {"kind": "standard_behavioural_theme", "text": None, "source_line": None,
                       "source_section": None}),
            "derivation": ("deterministic template tied to the posting's own responsibility line"
                           if linked else
                           "standard behavioural theme; no matching responsibility line in this posting"),
            "employer_supplied": False,
            "note": "Preparation prompt generated by this tool, NOT an employer-supplied question.",
        })
    return out[: int(_limits(cfg).get("max_behavioural_questions", 10))]


def motivation_questions(brief: dict, cfg: dict) -> list[dict]:
    job = brief.get("job") or {}
    out = []
    for i, template in enumerate(cfg["question_bank"]["motivation_templates"], start=1):
        out.append({
            "id": f"motiv-{i}",
            "bucket": "motivation",
            "prompt": template,
            "basis": {"kind": "job_record", "text": None, "source_line": None,
                      "source_section": None,
                      "job": {k: job.get(k) for k in ("company", "title", "location")}},
            "derivation": "deterministic template over the job record fields only",
            "employer_supplied": False,
            "note": "Preparation prompt generated by this tool, NOT an employer-supplied question.",
        })
    return out


def eligibility_questions(brief: dict) -> list[dict]:
    out = []
    for i, item in enumerate(brief.get("eligibility", []), start=1):
        out.append({
            "id": f"elig-{i}",
            "bucket": "eligibility",
            "prompt": "The posting states a condition on who may apply. Be ready to state your "
                      "position on it precisely, and do not go beyond what you can evidence.",
            "basis": {"kind": "posting_eligibility", "text": item["text"],
                      "source_line": item["source_line"], "source_section": None,
                      "resolved_status": item.get("status"),
                      "owner_source": item.get("owner_source"),
                      "owner_source_line": item.get("owner_source_line")},
            "derivation": "deterministic template over the posting's own eligibility line",
            "employer_supplied": False,
            "note": "Preparation prompt generated by this tool, NOT an employer-supplied question.",
        })
    return out


def likely_questions(brief: dict, cfg: dict) -> list[dict]:
    items = (technical_questions(brief, cfg) + behavioural_questions(brief, cfg)
             + motivation_questions(brief, cfg) + eligibility_questions(brief))
    return items[: int(_limits(cfg).get("max_likely_questions", 30))]


def questions_to_ask_employer(brief: dict, cfg: dict) -> list[dict]:
    """Drawn only from the brief's own unknowns — never a claim about the employer."""
    out: list[dict] = []
    for item in brief.get("eligibility", []):
        if item.get("status") != "satisfied_by_owner_source":
            out.append({
                "basis": {"kind": "brief_eligibility_unknown", "source_line": item["source_line"],
                          "text": item["text"]},
                "prompt": "Ask how this condition is normally evidenced for this role.",
            })
    for risk in brief.get("risks_unknowns", []):
        if risk.get("severity") in ("major", "blocker"):
            out.append({
                "basis": {"kind": "brief_risk", "detail": risk.get("detail"),
                          "action": risk.get("action")},
                "prompt": "Ask a clarifying question about this uncertainty before relying on it.",
            })
    research = brief.get("research") or {}
    if research.get("status") != "provided":
        out.append({
            "basis": {"kind": "research_gap", "detail": "no cited company research is available"},
            "prompt": "Ask about the team structure, on-call or shift pattern, and what the first "
                      "three months look like — nothing here is known from a source.",
        })
    return out[: int(_limits(cfg).get("max_questions_to_ask_employer", 8))]


# --------------------------------------------------------------------------- #
# evidence-backed talking points
# --------------------------------------------------------------------------- #

def _terms_for(text: str, cfg: dict) -> list[str]:
    wf = cvw.load_config(CONTROL_PLANE / cfg["cv_workflow_config"])
    return cvw.jd_terms(wf, text or "")


def match_evidence(requirement_text: str, evidence: list[dict], cfg: dict) -> list[dict]:
    """Canonical lines that share at least one *specific* term with the requirement.

    A match on a general domain word alone ("security", "data", "analysis") is not
    evidence — it would make almost any requirement look sourced. ``general_terms``
    in the config removes those, and a line only qualifies when a term outside that
    list matches. That is what keeps ``owner_input_required`` honest.
    """
    terms = _terms_for(requirement_text, cfg)
    matching = cfg.get("evidence_matching", {})
    general = {t.casefold() for t in matching.get("general_terms", [])}
    weights = matching.get("section_weight", {})
    scored = []
    for item in evidence:
        hits = cvw.term_hits(item["quote"], terms)
        specific = [h for h in hits if h.casefold() not in general]
        if len(specific) < int(matching.get("min_matched_terms", 1)):
            continue
        scored.append({
            "quote": item["quote"],
            "source": item["source"],
            "source_line": item["source_line"],
            "section": item["section"],
            "matched_terms": specific,
            "score": len(specific) + float(weights.get(item["section"] or "", 0)),
        })
    scored.sort(key=lambda e: (-e["score"], e["source_line"]))
    return scored


def _scaffold_drop(term: str, evidence: list[dict], cfg: dict,
                   used_keys: set[tuple], limit: int = 2) -> list[dict]:
    picked = []
    for item in evidence:
        key = (item["source"], item["source_line"])
        if key in used_keys:
            continue
        if cvw.term_hits(item["quote"], [term]):
            used_keys.add(key)
            picked.append({"quote": item["quote"], "source": item["source"],
                           "source_line": item["source_line"], "section": item["section"],
                           "matched_terms": [term]})
            if len(picked) >= limit:
                break
    return picked


def _education_quotes(evidence: list[dict], used_keys: set[tuple], cfg: dict,
                      limit: int = 2) -> list[dict]:
    """Canonical qualification lines — evidence for a degree/qualification requirement.

    A degree requirement is answered by the canonical qualification material itself;
    the general-term filter that protects every other match would otherwise suppress
    it, because "degree"/"university" appear in almost any posting. The canonical CV
    gives each qualification its own heading, so the section patterns come from the
    config rather than assuming a single "Education" section exists.
    """
    patterns = [p.casefold() for p in
                cfg.get("evidence_matching", {}).get("qualification_section_patterns", [])]
    picked = []
    for item in evidence:
        section = (item["section"] or "").casefold()
        if not any(re.search(p, section) for p in patterns):
            continue
        key = (item["source"], item["source_line"])
        if key in used_keys:
            continue
        used_keys.add(key)
        picked.append({"quote": item["quote"], "source": item["source"],
                       "source_line": item["source_line"], "section": item["section"],
                       "matched_terms": []})
        if len(picked) >= limit:
            break
    return picked


def talking_points(brief: dict, evidence: list[dict], cfg: dict) -> list[dict]:
    """One talking point per essential requirement, quoting canonical lines verbatim."""
    out: list[dict] = []
    used_keys: set[tuple] = set()
    limit = int(_limits(cfg).get("max_talking_points", 12))

    # 1. opening pitch, built only from the canonical Profile line(s)
    profile_line = next((e for e in evidence
                         if (e["section"] or "").casefold() == "profile"), None)
    if profile_line:
        used_keys.add((profile_line["source"], profile_line["source_line"]))
        out.append({
            "id": "tp-opening",
            "use": "opening pitch / 'tell me about yourself'",
            "requirement": None,
            "status": "evidence_backed",
            "quotes": [{"quote": profile_line["quote"], "source": profile_line["source"],
                        "source_line": profile_line["source_line"],
                        "section": profile_line["section"], "matched_terms": []}],
            "scaffold": "Read the canonical profile line aloud, in its own words, then stop. "
                        "Do not add anything the line does not say.",
            "owner_action": None,
        })

    for req in brief.get("requirements", []):
        if req.get("kind") != "essential":
            continue
        if len(out) >= limit:
            break
        category = _category_for(req.get("text"), cfg)["id"]
        if category == "qualification_education":
            quotes = _education_quotes(evidence, used_keys, cfg)
            match_basis = "requirement category 'qualification_education' resolved to the " \
                          "canonical Education section (no term matching used)"
        else:
            ranked = match_evidence(req["text"], evidence, cfg)
            quotes = [q for q in ranked
                      if (q["source"], q["source_line"]) not in used_keys][:2]
            for q in quotes:
                used_keys.add((q["source"], q["source_line"]))
            match_basis = "specific-term overlap against the posting's own vocabulary"
        if quotes:
            out.append({
                "id": f"tp-req-{len(out) + 1}",
                "use": "evidence-backed answer",
                "requirement": {"text": req["text"], "source_line": req["source_line"],
                                "source_section": req.get("source_section")},
                "status": "evidence_backed",
                "match_basis": match_basis,
                "quotes": [{"quote": q["quote"], "source": q["source"],
                            "source_line": q["source_line"], "section": q.get("section"),
                            "matched_terms": q["matched_terms"]}
                           for q in quotes],
                "scaffold": "State plainly what the posting asks for, then quote the canonical "
                            "evidence above. Say what you have not done if the evidence does not "
                            "cover it.",
                "owner_action": None,
            })
        else:
            out.append({
                "id": f"tp-req-{len(out) + 1}",
                "use": "gap to prepare",
                "requirement": {"text": req["text"], "source_line": req["source_line"],
                                "source_section": req.get("source_section")},
                "status": "owner_input_required",
                "match_basis": "no canonical evidence matched",
                "quotes": [],
                "scaffold": "No canonical source in cv.md evidences this requirement.",
                "owner_action": f"Decide how to answer the requirement \"{req['text']}\": either "
                                f"add real evidence to the canonical sources, or prepare to say "
                                f"plainly that you have not done it. This pack will not invent one.",
            })
    return out[:limit]


# --------------------------------------------------------------------------- #
# unknowns and truth checks
# --------------------------------------------------------------------------- #

def collect_unknowns(brief: dict, talking: list[dict], cfg: dict) -> list[dict]:
    out: list[dict] = []
    for item in brief.get("eligibility", []):
        if item.get("status") != "satisfied_by_owner_source":
            out.append({"kind": "eligibility_unknown", "detail": item["text"],
                        "source": f"JobBrief eligibility line {item['source_line']}",
                        "action": "State your position yourself; the build will not infer it."})
    for risk in brief.get("risks_unknowns", []):
        out.append({"kind": f"brief_risk:{risk.get('kind')}", "detail": risk.get("detail"),
                    "source": "JobBrief risks_unknowns",
                    "action": risk.get("action"),
                    "severity": risk.get("severity")})
    research = brief.get("research") or {}
    if research.get("status") != "provided":
        out.append({"kind": "research_needed",
                    "detail": "No cited company/role research is available for this posting.",
                    "source": "JobBrief research.status",
                    "action": "Supply a cited research file, or ask these questions in the "
                              "interview rather than assuming an answer."})
    for tp in talking:
        if tp["status"] == "owner_input_required":
            out.append({"kind": "requirement_without_canonical_evidence",
                        "detail": tp["requirement"]["text"],
                        "source": f"JobBrief requirement line {tp['requirement']['source_line']}",
                        "action": tp["owner_action"]})
    return out[: int(_limits(cfg).get("max_unknowns", 40))]


def candidate_claim_violations(pack: dict) -> list[dict]:
    """Scan generated (non-quoted) text for a candidate claim that was never sourced.

    Quoted canonical lines are excluded by construction: only ``prompt``,
    ``scaffold``, ``note``, ``owner_action``, ``use`` and ``derivation`` fields are
    scanned, and none of them may contain a first-person claim pattern.
    """
    violations: list[dict] = []
    scanned_fields = ("prompt", "scaffold", "note", "owner_action", "use", "derivation",
                      "theme", "category")
    sections = [
        ("sections.technical_prep", pack.get("sections", {}).get("technical_prep", [])),
        ("sections.behavioural_prep", pack.get("sections", {}).get("behavioural_prep", [])),
        ("sections.likely_questions", pack.get("sections", {}).get("likely_questions", [])),
        ("sections.evidence_backed_talking_points",
         pack.get("sections", {}).get("evidence_backed_talking_points", [])),
        ("sections.questions_to_ask_employer",
         pack.get("sections", {}).get("questions_to_ask_employer", [])),
    ]
    for where, items in sections:
        for item in items:
            for field in scanned_fields:
                value = item.get(field)
                if not isinstance(value, str):
                    continue
                for pattern in ji.CANDIDATE_CLAIM_PATTERNS:
                    if re.search(pattern, value, re.I):
                        violations.append({"where": where, "id": item.get("id"),
                                           "field": field, "pattern": pattern,
                                           "text": value[:200]})
    return violations


def quote_violations(pack: dict, cfg: dict) -> list[dict]:
    """Every quoted line must exist verbatim at the cv.md line it claims."""
    index = canonical_line_index(cfg)
    bad: list[dict] = []
    for tp in pack.get("sections", {}).get("evidence_backed_talking_points", []):
        for q in tp.get("quotes", []):
            actual = index.get(q.get("source_line"))
            if actual is None:
                bad.append({"id": tp.get("id"), "reason": "source line does not exist",
                            "source_line": q.get("source_line")})
                continue
            stripped = actual[1:].strip() if actual.startswith(("-", "*")) else actual
            if q.get("quote") != stripped:
                bad.append({"id": tp.get("id"), "reason": "quote is not verbatim at that line",
                            "source_line": q.get("source_line"),
                            "expected": stripped[:160], "got": str(q.get("quote"))[:160]})
    return bad


# --------------------------------------------------------------------------- #
# the pack
# --------------------------------------------------------------------------- #

def build_prep_pack(cfg: dict, brief: dict, *, brief_path: str | Path | None = None,
                    research_file: str | Path | None = None,
                    stamp: str | None = None) -> dict:
    stamp = stamp or dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    evidence = canonical_evidence(cfg)

    research_facts = brief.get("company_facts", [])
    research_meta = dict(brief.get("research") or {})
    research_source = "JobBrief (career-ops/job_intelligence.py)"
    if research_file:
        extra = ji.research_brief(ji_config(cfg), brief.get("job") or {},
                                  research_file=research_file)
        research_facts = extra.get("facts", [])
        research_meta = {k: v for k, v in extra.items() if k != "facts"}
        research_source = f"research file {research_file} via job_intelligence.research_brief"

    tech = technical_questions(brief, cfg)
    behav = behavioural_questions(brief, cfg)
    likely = likely_questions(brief, cfg)
    talking = talking_points(brief, evidence, cfg)
    employer_q = questions_to_ask_employer(brief, cfg)
    unknowns = collect_unknowns(brief, talking, cfg)

    cv_paths = cvw.source_paths(cv_config(cfg))
    job_key = sha256_text(json.dumps(brief.get("job") or {}, sort_keys=True))[:8]
    pack = {
        "schema_version": cfg.get("schema_version", 1),
        "prep_id": f"ip-{stamp}-{job_key}",
        "generated_at": now_utc(),
        "generator": "career-ops/interview_prep.py",
        "job": brief.get("job"),
        "provenance": {
            "brief": {"path": str(brief_path) if brief_path else None,
                      "brief_id": brief.get("brief_id"),
                      "sha256": sha256_file(brief_path) if brief_path else None,
                      "generator": brief.get("generator"),
                      "job_description": (brief.get("provenance") or {}).get("job_description")},
            "canonical_owner_sources": {
                "cv.md": {"path": str(cv_paths["cv_md"]), "sha256": sha256_file(cv_paths["cv_md"])},
                "config/profile.yml": {"path": str(cv_paths["profile"]),
                                       "sha256": sha256_file(cv_paths["profile"])},
                "config/cv-facts.json": {"path": str(cv_paths["cv_facts"]),
                                         "sha256": sha256_file(cv_paths["cv_facts"])},
            },
            "canonical_evidence_lines": len(evidence),
            "research_source": research_source,
            "question_derivation": "deterministic templates over the posting's own text "
                                   "(career-ops/interview_prep_config.json question_bank)",
        },
        "research": {**research_meta, "facts_available": len(research_facts),
                     "facts": research_facts},
        "sections": {
            "technical_prep": tech,
            "behavioural_prep": behav,
            "likely_questions": likely,
            "evidence_backed_talking_points": talking,
            "questions_to_ask_employer": employer_q,
            "unknowns": unknowns,
        },
        "counts": {
            "technical_prep": len(tech),
            "behavioural_prep": len(behav),
            "likely_questions": len(likely),
            "talking_points": len(talking),
            "talking_points_evidence_backed": sum(1 for t in talking
                                                  if t["status"] == "evidence_backed"),
            "talking_points_owner_input_required": sum(1 for t in talking
                                                       if t["status"] == "owner_input_required"),
            "questions_to_ask_employer": len(employer_q),
            "unknowns": len(unknowns),
            "source_lines_quoted": sum(len(t.get("quotes", [])) for t in talking),
        },
        "truth_rules": cfg.get("truth_rules", []),
        "candidate_claims": [],
        "not_performed": cfg.get("not_performed", []),
        "external_actions_taken": [],
        "interview_scheduled": False,
        "interview_attended": False,
    }
    pack["validation"] = validate_pack(pack, cfg)
    pack["candidate_claim_violations"] = candidate_claim_violations(pack)
    pack["quote_violations"] = quote_violations(pack, cfg)
    pack["ok"] = bool(pack["validation"]["ok"]) and not pack["candidate_claim_violations"] \
        and not pack["quote_violations"]
    return pack


def validate_pack(pack: dict, cfg: dict | None = None) -> dict:
    """Structural + truth checks, independent of how the pack was produced."""
    errors: list[str] = []
    warnings: list[str] = []

    for key in ("schema_version", "prep_id", "generated_at", "generator", "job",
                "provenance", "sections", "counts", "candidate_claims",
                "not_performed", "external_actions_taken"):
        if key not in pack:
            errors.append(f"missing required key: {key}")
    if not isinstance(pack.get("job"), dict):
        errors.append("job must be an object")
    else:
        for key in ("title", "company"):
            if not pack["job"].get(key):
                warnings.append(f"job.{key} is not stated in the brief")

    sections = pack.get("sections") or {}
    for name in ("technical_prep", "behavioural_prep", "likely_questions",
                 "evidence_backed_talking_points", "questions_to_ask_employer", "unknowns"):
        if not isinstance(sections.get(name), list):
            errors.append(f"sections.{name} must be a list")

    for item in sections.get("likely_questions", []) or []:
        for key in ("id", "bucket", "prompt", "basis", "derivation", "employer_supplied",
                    "note"):
            if key not in item:
                errors.append(f"question {item.get('id')} missing {key}")
        if item.get("employer_supplied") is not False:
            errors.append(f"question {item.get('id')} claims to be employer-supplied")
        if "NOT" not in (item.get("note") or ""):
            errors.append(f"question {item.get('id')} does not disclaim employer origin")

    for tp in sections.get("evidence_backed_talking_points", []) or []:
        for key in ("id", "use", "status", "quotes", "scaffold"):
            if key not in tp:
                errors.append(f"talking point {tp.get('id')} missing {key}")
        if tp.get("status") not in ("evidence_backed", "owner_input_required"):
            errors.append(f"talking point {tp.get('id')} has an unknown status")
        if tp.get("status") == "evidence_backed" and not tp.get("quotes"):
            errors.append(f"talking point {tp.get('id')} claims evidence with no quote")
        if tp.get("status") == "owner_input_required" and not tp.get("owner_action"):
            errors.append(f"talking point {tp.get('id')} has no owner action")
        for q in tp.get("quotes", []) or []:
            for key in ("quote", "source", "source_line"):
                if key not in q:
                    errors.append(f"talking point {tp.get('id')} quote missing {key}")

    if pack.get("candidate_claims"):
        errors.append("candidate_claims must be empty")
    if pack.get("external_actions_taken"):
        errors.append("external_actions_taken must be empty")
    if pack.get("interview_scheduled") or pack.get("interview_attended"):
        errors.append("the prep agent must never record a scheduled or attended interview")

    return {"ok": not errors, "errors": errors, "warnings": warnings,
            "checked_sections": list(sections.keys())}


# --------------------------------------------------------------------------- #
# commands
# --------------------------------------------------------------------------- #

def _refuse_to_overwrite_inputs(args, out_paths: list[Path]) -> list[dict]:
    inputs = []
    for attr in ("brief", "jd_file", "job_record", "research_file"):
        value = getattr(args, attr, None)
        if value:
            inputs.append((attr, Path(value).resolve()))
    problems = []
    for flag, inp in inputs:
        for out in out_paths:
            if out.resolve() == inp:
                problems.append({"input_flag": flag, "path": str(inp),
                                 "reason": "output path would overwrite an input file"})
    return problems


def _write_pack(pack: dict, out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    pack_path = out_dir / "interview_prep_pack.json"
    pack_path.write_text(json.dumps(pack, indent=2, ensure_ascii=False, default=str),
                         encoding="utf-8")
    md = [f"# Interview prep pack — {pack['prep_id']}", "",
          f"Generated: {pack['generated_at']}",
          f"Role: {pack.get('job', {}).get('title')} @ {pack.get('job', {}).get('company')}",
          f"Brief: {pack['provenance']['brief'].get('brief_id')}",
          "",
          "Every question below is a preparation prompt generated by a deterministic",
          "template from the posting's own text. None of them is a question the",
          "employer supplied. Nothing here was sent to anyone.", ""]
    for name, items in (("Technical preparation", pack["sections"]["technical_prep"]),
                        ("Behavioural preparation", pack["sections"]["behavioural_prep"])):
        md += [f"## {name}", ""]
        for item in items:
            md.append(f"- **{item['id']}** {item['prompt']}")
            basis = item.get("basis") or {}
            if basis.get("text"):
                md.append(f"  - posting line {basis['source_line']}: {basis['text']}")
        md.append("")
    md += ["## Likely questions (index — full detail in the sections above)", ""]
    for n, item in enumerate(pack["sections"]["likely_questions"], start=1):
        basis = item.get("basis") or {}
        suffix = (f"  (posting line {basis['source_line']})" if basis.get("source_line")
                  else "  (not posting-derived)")
        md.append(f"{n}. [{item['bucket']}/{item['id']}] {item['prompt']}{suffix}")
    md.append("")
    md += ["## Evidence-backed talking points", ""]
    for tp in pack["sections"]["evidence_backed_talking_points"]:
        md.append(f"- **{tp['id']}** ({tp['status']}) — {tp['use']}")
        if tp.get("requirement"):
            md.append(f"  - posting line {tp['requirement']['source_line']}: "
                      f"{tp['requirement']['text']}")
        for q in tp.get("quotes", []):
            md.append(f"  - cv.md:{q['source_line']} — {q['quote']}")
        if tp.get("owner_action"):
            md.append(f"  - owner action: {tp['owner_action']}")
    md += ["", "## Unknowns", ""]
    md += [f"- ({u['kind']}) {u.get('detail')}" for u in pack["sections"]["unknowns"]]
    (out_dir / "interview_prep_pack.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    return {"pack_path": str(pack_path), "pack_markdown": str(out_dir / "interview_prep_pack.md")}


def cmd_pack(args) -> int:
    cfg = load_config(args.config)
    try:
        brief = load_brief(args.brief)
    except (BriefError, json.JSONDecodeError) as exc:
        emit({"ok": False, "reason": f"{type(exc).__name__}: {exc}"})
        return 1
    stamp = args.stamp or dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_dir = Path(args.out) if args.out else (runtime_dir(cfg) / stamp)
    collisions = _refuse_to_overwrite_inputs(args, [out_dir / "interview_prep_pack.json",
                                                    out_dir / "interview_prep_pack.md"])
    if collisions:
        emit({"ok": False, "reason": "refusing to write over an input file",
              "collisions": collisions, "writes_performed": []})
        return 1
    pack = build_prep_pack(cfg, brief, brief_path=args.brief,
                           research_file=args.research_file, stamp=stamp)
    paths = _write_pack(pack, out_dir)
    emit({"ok": pack["ok"], **paths, "prep_id": pack["prep_id"], "job": pack["job"],
          "counts": pack["counts"], "validation": pack["validation"],
          "candidate_claim_violations": pack["candidate_claim_violations"],
          "quote_violations": pack["quote_violations"],
          "external_actions_taken": []})
    return 0 if pack["ok"] else 1


def cmd_from_job(args) -> int:
    """Resolve a job from Career Ops, brief it, then build the prep pack."""
    cfg = load_config(args.config)
    wf = cvw.load_config(CONTROL_PLANE / cfg["cv_workflow_config"])
    profiles = tw.load_profiles(str(profiles_path(cfg)))
    resolved = cvw.resolve_job(wf, profiles, region=args.region, job_id=args.id,
                               url=args.url, row=args.row,
                               pipeline_index=args.pipeline_index,
                               record_file=args.job_record)
    if not resolved.get("ok"):
        emit(resolved)
        return 1
    job = resolved["job"]
    if args.jd_file:
        p = Path(args.jd_file)
        if not p.exists():
            emit({"ok": False, "reason": f"job-description file not found: {p}"})
            return 1
        jd_text = read_text(p)
        jd_source = f"explicit file {p}"
    else:
        jd_text = resolved.get("jd_text") or ""
        jd_source = resolved.get("jd_source")
    stamp = args.stamp or dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    brief = ji.build_brief(ji_config(cfg), job=job, jd_text=jd_text, jd_source=jd_source,
                           research_file=args.research_file, stamp=stamp)
    out_dir = Path(args.out) if args.out else (runtime_dir(cfg) / stamp)
    collisions = _refuse_to_overwrite_inputs(args, [out_dir / "interview_prep_pack.json",
                                                    out_dir / "interview_prep_pack.md"])
    if collisions:
        emit({"ok": False, "reason": "refusing to write over an input file",
              "collisions": collisions, "writes_performed": []})
        return 1
    brief_path = out_dir / "job_brief.json"
    out_dir.mkdir(parents=True, exist_ok=True)
    brief_path.write_text(json.dumps(brief, indent=2, ensure_ascii=False, default=str),
                          encoding="utf-8")
    pack = build_prep_pack(cfg, brief, brief_path=brief_path, stamp=stamp)
    paths = _write_pack(pack, out_dir)
    emit({"ok": pack["ok"], "brief_path": str(brief_path), **paths,
          "prep_id": pack["prep_id"], "job": pack["job"], "counts": pack["counts"],
          "brief_validation_ok": brief["validation"]["ok"],
          "validation": pack["validation"],
          "candidate_claim_violations": pack["candidate_claim_violations"],
          "quote_violations": pack["quote_violations"],
          "external_actions_taken": []})
    return 0 if pack["ok"] else 1


def cmd_validate(args) -> int:
    cfg = load_config(args.config)
    pack = json.loads(read_text(args.pack))
    # Re-derive the truth checks against the live canonical sources so a pack
    # cannot be validated against its own claims.
    result = validate_pack(pack, cfg)
    try:
        result["quote_violations"] = quote_violations(pack, cfg)
    except Exception as exc:  # noqa: BLE001 - absent install is reported truthfully
        result["quote_violations"] = []
        result["quote_check_error"] = f"{type(exc).__name__}: {exc}"
    result["candidate_claim_violations"] = candidate_claim_violations(pack)
    result["ok"] = bool(result["ok"]) and not result["quote_violations"] \
        and not result["candidate_claim_violations"]
    emit(result)
    return 0 if result["ok"] else 1


def cmd_schema(args) -> int:
    cfg = load_config(args.config)
    path = pack_schema_path(cfg)
    emit({"pack_schema": str(path), "exists": path.exists(),
          "brief_schema": str(CONTROL_PLANE / cfg["brief_schema"]),
          "config_path": cfg["_config_path"],
          "schema": json.loads(read_text(path)) if path.exists() else None})
    return 0 if path.exists() else 1


def cmd_status(args) -> int:
    cfg = load_config(args.config)
    cv_paths = cvw.source_paths(cv_config(cfg))
    runtime = runtime_dir(cfg)
    packs = sorted(runtime.glob("*/interview_prep_pack.json")) if runtime.exists() else []
    return_status = {
        "ok": True,
        "generated_at": now_utc(),
        "config": cfg["_config_path"],
        "runtime_dir": str(runtime),
        "packs_built": len(packs),
        "latest_pack": str(packs[-1]) if packs else None,
        "canonical_sources": {k: {"path": str(p), "exists": p.exists()} for k, p in cv_paths.items()},
        "question_bank_categories": [c["id"] for c in cfg["question_bank"]["categories"]],
        "behavioural_themes": [b["id"] for b in cfg["question_bank"]["behavioural"]],
        "not_performed": cfg["not_performed"],
        "external_actions_available": [],
    }
    emit(return_status)
    return 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Interview Prep Agent (roster B22)")
    ap.add_argument("--config", default=None)
    sub = ap.add_subparsers(dest="command", required=True)

    p = sub.add_parser("pack")
    p.add_argument("--brief", required=True)
    p.add_argument("--research-file")
    p.add_argument("--out")
    p.add_argument("--stamp")
    p.set_defaults(fn=cmd_pack)

    p = sub.add_parser("from-job")
    p.add_argument("--region", default="uk")
    p.add_argument("--id"); p.add_argument("--url"); p.add_argument("--row", type=int)
    p.add_argument("--pipeline-index", type=int); p.add_argument("--job-record")
    p.add_argument("--jd-file"); p.add_argument("--research-file")
    p.add_argument("--out"); p.add_argument("--stamp")
    p.set_defaults(fn=cmd_from_job)

    p = sub.add_parser("validate")
    p.add_argument("--pack", required=True)
    p.set_defaults(fn=cmd_validate)

    p = sub.add_parser("schema"); p.set_defaults(fn=cmd_schema)
    p = sub.add_parser("status"); p.set_defaults(fn=cmd_status)

    args = ap.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    raise SystemExit(main())
